%%bash

#esto va en un makefile a priori
pip install --upgrade pip
pip install farm-haystack[inference]
pip install torch torchvision torchaudio
pip install -U sentence-transformers
pip install --upgrade langchain
