%%bash

#esto va en un makefile a priori
install_package:
	@pip install --upgrade pip
	@pip install farm-haystack
	@pip install farm-haystack[inference]
	@pip install torch torchvision torchaudio
	@pip install -U sentence-transformers
	@pip install --upgrade langchain
	@pip install fastapi
	@pip install uvicorn
	@pip install nltk
	@pip install spacey
	@python -m spacy download en_core_web_sm
